Repository chingu-voyage7/Bears-Team-17, pull requests merged in 2018-12, with the labels that each got.

#5 Add db models (spintronic)
  package-lock.json
  package.json
  sample.env
  server/index.js
  server/models/answers.js
  server/models/db.js
  server/models/questions.js
  server/models/users.js
Labels: discussing, enhancement

#10 Bug: reference to db models
  server/models/answers.js
  server/models/questions.js
Labels: bug

#6 Linting
  .eslintrc.json
  package-lock.json
  package.json
  server/index.js
  server/models/answers.js
  server/models/db.js
  server/models/questions.js
  server/models/users.js
Labels: tools

#12 Testing:FE
  .gitignore
  README.md
  client/package-lock.json
  client/package.json
  client/src/MyComponent.js
  client/src/MyComponent.test.js
  client/src/jest.config.js
  client/src/jest.setup.js
  package-lock.json
  package.json
Labels: testing

#13 Feature add api post question
  server/index.js
  server/models/answers.js
  server/models/db.js
  server/models/questions.js
  server/models/users.js
  server/routes/api.js
Labels: enhancement

#14 Feature: GET API question - spintronic
  server/models/answers.js
  server/models/questions.js
  server/models/users.js
  server/routes/api.js
Labels: enhancement
